- name: install nginx
  hosts: localhost
  user: centos
  tasks:  
  - name: cloning the repo
    git:
      repo: https://github.com/DilipJadhav/ansible-tower
      dest: /home/centos/ansible

  - name: installing nginx
    command: python /home/centos/ansible/ansible-tower/nginx.py
