- name: install nginx
  hosts: test
  user: acm
  become: yes
  tasks:  
  - name: add nginx repo
    yum:
      name: epel-release
      state: present
  - name: installing nginx
    yum:
      name: nginx
      state: present
