- name: install nginx
  hosts: nginx-server
  user: centos
  become: yes
  tasks:  
  - name: cloning the repo
    git:
      repo: https://github.com/DilipJadhav/ansible-tower
      dest: /home/centos

  - name: installing nginx
    shell: ./home/centos/ansible-tower/nginx.py
