- name: install nginx
  hosts: localhost
  user: centos
  tasks:  
 # - name: cloning the repo
 #   command: git clone https://github.com/DilipJadhav/ansible-tower

  - name: installing nginx
    script:  /home/centos/ansible-tower/aws-ansible/nginx.py
