- name: install nginx
  hosts: localhost
  user: admin
  tasks:  
  - name: cloning the repo
    git:
      repo: 'https://github.com/DilipJadhav/ansible-tower.git'
      dest: $HOME/ansible-tower
      
  - name: install nginx
    command: python /home/admin/ansible-tower/aws-ansible/nginx.py

