- name: install nginx
  hosts: test
  user: centos
  tasks:  
  - name: cloning the repo
    git:
      repo: 'https://github.com/DilipJadhav/ansible-tower.git'
      dest: $HOME/ansible-tower
      
  - name: nstall nginx
    command: python /home/centos/ansible-tower/aws-ansible/nginx.py

