- name: install nginx
  hosts: test
  user: acm
  become: yes
  tasks:  
  - name: add nginx repo
    pkg:
      name: epel-release
      state: present
  - name: installing nginx
    pkg:
      name: nginx
      state: present
