- name: install nginx
  hosts: localhost
  user: centos
  tasks:  
  - name: cloning the repo
    git:
      repo: https://github.com/DilipJadhav/ansible-tower
      dest: $HOME/ansible

  - name: installing nginx
    shell: ./$HOME/ansible/ansible-tower/nginx.py
