- name: install nginx
  hosts: nginx-server
  user: acm
  become: yes
  tasks:  
  - name: update the repo
    apt:
      update_cache: yes

  - name: installing nginx
    apt:
      name: nginx
      state: present
