- name: install nginx
  hosts: localhost
  user: centos
  become: yes
  gather_facts: no
  tasks:  
  - name: cloning the repo
    git:
      repo: https://github.com/DilipJadhav/ansible-tower
      dest: /home/centos

  - name: installing nginx
    shell: ./home/centos/ansible-tower/nginx.py
