- name: install nginx
  hosts: nginx
  user: centos
  tasks:  
  - name: cloning the repo
    git:
      repo: 'https://github.com/DilipJadhav/ansible-tower.git'
      dest: /home/centos/ansible-tower
  
  - name: changing mode of ec2.py
    command: sudo chmod 777 /home/centos/ansible-tower/aws-ansible/inventory/aws/hosts/ec2.py        
  
  - name: install nginx
    command: python /home/centos/ansible-tower/aws-ansible/nginx.py --no-confirm
    environment:
      AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID')}}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY')}}"  
